language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "aeronica-github"
    token:
      secure: $GITHUB_TOKEN
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube -Dsonar.login=$SONAR_LOGIN
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'